### PR TITLE
add option for hide fallback lang

### PR DESCRIPTION
**Pull request by MohamedTaha880**

### CODE REVIEW

**Review by Aldus83 — CHANGES_REQUESTED** [review]
@MohamedTaha880  we should discuss this, I fear it can break several sites

**Review by Aldus83 — CHANGES_REQUESTED** [review]
please change variable as $use_fallback_language so it's more understandable its scope

**Comment by Aldus83** [comment]
@MohamedTaha880 let's close this one, has been here for a while

**Comment by MohamedTaha880** [comment]
Hi @Aldus83 
Done!

**Pull request merged**
